baseURL = "https://cattle0horse.github.io"
languageCode = "en-us"
title = "CattleHorse's Blog" # for rss
theme = "yinyang"
DefaultContentLanguage = "cn"

[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2
#   [languages.en]
#     contentDir = "content/en"
#     languageName = "English"
#     weight = 1

# 代码块
# 公式 https://gohugo.io/content-management/mathematics/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "tango"
    tabWidth = 2


[params]
  # disqus = "help"   # disqus account name
  # extraHead = ''
  headTitle = "CattleHorse's Blog"
  description = "By accumulating small steps, one can reach a thousand miles."
  mainSections = ["posts"]
  favicon = "/logo.png"
  lazyImage = true
  # extraCSSFiles = ["css/foo.css", "css/bar.css"]
  extraCSSFiles = ["css/background.css"]
  math = false # 让frontmatter中的math=true时才生效

# footer(通过CSS修改至header下方)
[[params.socials]]
  name = "RSS"
  link = "/index.xml"
[[params.socials]]
  name = "Github"
  link = "https://github.com/cattle0horse"
