baseURL = "https://cattle0horse.github.io"
languageCode = "en-us"
title = "CattleHorse's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2
#   [languages.en]
#     contentDir = "content/en"
#     languageName = "English"
#     weight = 1

# 代码块
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "tango"
    tabWidth = 2

[params]
  # disqus = "help"   # disqus account name
  # extraHead = ''
  headTitle = "CattleHorse's Blog"
  description = "By accumulating small steps, one can reach a thousand miles."
  mainSections = ["posts"]
  favicon = "/logo.png"
  lazyImage = true
  # extraCSSFiles = ["css/foo.css", "css/bar.css"]

# footer(通过CSS修改至header下方)
[[params.socials]]
  name = "RSS"
  link = "/index.xml"
[[params.socials]]
  name = "About"
  link = "https://github.com/cattle0horse"
