name: pages-auto-build-deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:
    # schedule:
        # Runs everyday at 8:00 AM
        # - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: "0.145.0"
                  extended: true

            - name: Build
              run: hugo --minify

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.GH_PAGE_ACTION_TOKEN  }}
                  EXTERNAL_REPOSITORY: Cattle0Horse/Cattle0Horse.github.io # Github Pages repo
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./public
                  commit_message: ${{ github.event.head_commit.message }}
